export const LOAD_BOOKMARKS = 'LOAD_BOOKMARKS';
export const LOAD_BOOKMARKS_SUCCESS = 'LOAD_BOOKMARKS_SUCCESS';
export const LOAD_BOOKMARKS_ERROR = 'LOAD_BOOKMARKS_ERROR';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';

export const ARCHIVE_BOOKMARK = 'ARCHIVE_BOOKMARK';
export const ARCHIVE_BOOKMARK_SUCCESS = 'ARCHIVE_BOOKMARK_SUCCESS';
export const ARCHIVE_BOOKMARK_ERROR = 'ARCHIVE_BOOKMARK_ERROR';

export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';
